[package]
name = "lets-encrypt-warp"
version = "0.0.1"
authors = ["David Roundy <daveroundy@gmail.com>"]
edition = "2018"

[dependencies]

acme-client = "0.5.3"
warp = { version = "0.1.16", features = ["tls"] }
