[package]
name = "lets-encrypt-warp"
version = "0.0.5"
authors = ["David Roundy <daveroundy@gmail.com>"]
edition = "2018"

description = "Simple use of letsencrypt.org with warp"
license = "Apache-2.0/MIT"
readme = "README.md"
repository = "https://github.com/droundy/lets-encrypt-warp"

[dependencies]

acme-client = "0.5.3"
warp = { version = "0.1.16", features = ["tls"] }
x509-parser = { git = "https://github.com/rusticata/x509-parser" }
